name: Fern Docs Generation

on:
  push:
    branches: [main]
    paths:
      - "backend/airweave/api/**/*.py"
      - "frontend/src/components/icons/apps/**"
      - "backend/airweave/platform/entities/**"
      - "backend/airweave/platform/sources/**"
      - "backend/airweave/platform/configs/auth.py"
      - "fern/**"
      - ".github/workflows/fern-docs.yml"
  workflow_dispatch:

jobs:
  generate-docs:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -

      - name: Install Python dependencies
        working-directory: ./backend
        run: poetry install

      - name: Install documentation dependencies
        run: pip install pyyaml

      - name: Generate connector documentation
        run: python fern/scripts/update_connector_docs.py

      - name: Generate OpenAPI spec
        working-directory: ./backend
        run: poetry run python ${{ github.workspace }}/fern/scripts/generate_openapi.py
        env:
          FIRST_SUPERUSER: "docs@example.com"
          FIRST_SUPERUSER_PASSWORD: "docs-password"
          ENCRYPTION_KEY: "docs-encryption-key"
          POSTGRES_HOST: "localhost"
          POSTGRES_USER: "postgres"
          POSTGRES_PASSWORD: "postgres"
          OPENAI_API_KEY: "sk-docs"
          LOCAL_DEVELOPMENT: "true"

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install Fern
        run: npm install -g fern-api

      - name: Update Fern OpenAPI definition
        run: |
          mkdir -p fern/definition
          echo "🌿 Updating Fern OpenAPI definition..."
          cp fern/definition/openapi.json fern/definition/openapi.json || echo "OpenAPI spec not found"

      - name: Generate Docs
        run: |
          cd fern
          fern generate --docs
        env:
          FERN_TOKEN: ${{ secrets.FERN_TOKEN }}

      - name: Commit changes
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add fern/docs/pages/connectors/ fern/docs.yml
          git diff --quiet && git diff --staged --quiet || git commit -m "docs: update documentation [skip ci]"
          git push
